#spring:
#  redis:
#    host: 192.168.1.3
server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: dev
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848  #nacos服务地址
          namespace:
          group: DEFAULT_GROUP
        config:
          server-addr: 127.0.0.1:8848
          namespace: 0bfc17b1-0ae4-4edc-a08d-867f34682c7f
          group: DEFAULT_GROUP
          file-extension: yml