#spring:
#  redis:
#    host: 192.168.1.3
server:
  port: 8081
spring:
  redis:
    host: 192.168.1.9
    port: 6379
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual